language: python

python:
  - 2.7
  - 3.6
  - 3.7

install:
  - pip install -e .
  - pip install -r travis-requirements.txt
  - pip install tox-travis

script:
  - flake8 timesheets
  - tox

after_success:
  - coverage combine
  - codecov
