language: python

virtualenv:
  system_site_packages: true

python:
  - "2.7"

install:
  - pip install -e .
  - pip install -r travis-requirements.txt

script:
  - flake8 timesheets
  - cd timesheets
  - coverage run -m unittest discover -p tests.py

after_success:
  - cd timesheets
  - codecov
